---
title: María Isabel Rodríguez Núñez
baseURL: "/"
params:
  none: ''
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
cloudinary_url: https://res.cloudinary.com/sgonzalez/image/upload/misabelrodriguez/
